const express=require('express'),pg=require('pg'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),path=require('path');
const app=express(); app.use(express.json()); app.use(express.static(path.join(__dirname,'public')));
const { Pool } = require("pg");const pool = new Pool({connectionString: process.env.DATABASE_URL,ssl: { rejectUnauthorized: false }});
console.log("DATABASE URL PRESENT:", !!process.env.DATABASE_URL);
const SECRET=process.env.JWT_SECRET||'change-me';
const companies=['Goluxigo','Partyclap','Opexminds','Propertylane','Dmccart','Claimreclaim','Swiftdocgo','Gopolicygo'];
async function init(){
 await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,phone VARCHAR(20) UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'member',active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT now());
 CREATE TABLE IF NOT EXISTS companies(id SERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL);
 CREATE TABLE IF NOT EXISTS tasks(id SERIAL PRIMARY KEY,task_code TEXT UNIQUE,company_id INT REFERENCES companies(id),assigned_to INT REFERENCES users(id),created_by INT REFERENCES users(id),task_name TEXT NOT NULL,admin_remarks TEXT,start_date DATE,end_date DATE,status TEXT DEFAULT 'Not Started',created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
 CREATE TABLE IF NOT EXISTS task_remarks(id SERIAL PRIMARY KEY,task_id INT REFERENCES tasks(id) ON DELETE CASCADE,user_id INT REFERENCES users(id),remark TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now());
 CREATE TABLE IF NOT EXISTS task_history(id SERIAL PRIMARY KEY,task_id INT REFERENCES tasks(id) ON DELETE CASCADE,version INT NOT NULL,changed_by INT REFERENCES users(id),snapshot JSONB NOT NULL,change_note TEXT,created_at TIMESTAMPTZ DEFAULT now());
 CREATE TABLE IF NOT EXISTS messages(id SERIAL PRIMARY KEY,sender_id INT REFERENCES users(id),receiver_id INT REFERENCES users(id),task_id INT REFERENCES tasks(id),body TEXT NOT NULL,read_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now());
 CREATE TABLE IF NOT EXISTS notifications(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id),task_id INT REFERENCES tasks(id),type TEXT,title TEXT,body TEXT,read_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now());`);
 for(const c of companies) await pool.query('INSERT INTO companies(name) VALUES($1) ON CONFLICT(name) DO NOTHING',[c]);
 const phone=process.env.ADMIN_PHONE||'9999999999', pass=process.env.ADMIN_PASSWORD||'ChangeMe123!', name=process.env.ADMIN_NAME||'Golden Circle Admin';
 const h=await bcrypt.hash(pass,10); await pool.query(`INSERT INTO users(name,phone,password_hash,role) VALUES($1,$2,$3,'admin') ON CONFLICT(phone) DO NOTHING`,[name,phone,h]);
}
async function auth(req,res,next){const t=(req.headers.authorization||'').replace('Bearer ','');try{const d=jwt.verify(t,SECRET);const {rows:[u]}=await pool.query('SELECT id,name,phone,role,active FROM users WHERE id=$1',[d.id]);if(!u||!u.active)return res.status(401).json({error:'Unauthorized'});req.user=u;next()}catch(e){res.status(401).json({error:'Unauthorized'})}}
function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Admin only'});next()}
async function snap(taskId,userId,note){const {rows:[t]}=await pool.query('SELECT * FROM tasks WHERE id=$1',[taskId]); const {rows:[v]}=await pool.query('SELECT COALESCE(MAX(version),0)+1 v FROM task_history WHERE task_id=$1',[taskId]); await pool.query('INSERT INTO task_history(task_id,version,changed_by,snapshot,change_note) VALUES($1,$2,$3,$4,$5)',[taskId,v.v,userId,t,note]);}
app.post('/api/login',async(req,res)=>{const {phone,password}=req.body;const {rows}=await pool.query('SELECT * FROM users WHERE phone=$1 AND active=true',[phone]);if(!rows[0]||!await bcrypt.compare(password,rows[0].password_hash))return res.status(401).json({error:'Invalid phone number or password'});const u=rows[0];res.json({token:jwt.sign({id:u.id,name:u.name,role:u.role,phone:u.phone},SECRET,{expiresIn:'7d'}),user:{id:u.id,name:u.name,role:u.role,phone:u.phone}})});
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/companies',auth,async(req,res)=>res.json((await pool.query('SELECT * FROM companies ORDER BY name')).rows));
app.get('/api/users',auth,admin,async(req,res)=>res.json((await pool.query("SELECT id,name,phone,role,active,created_at FROM users ORDER BY name")).rows));
app.post('/api/users',auth,admin,async(req,res)=>{const {name,phone,password,role='member'}=req.body;try{const h=await bcrypt.hash(password,10);const {rows}=await pool.query('INSERT INTO users(name,phone,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,phone,role,active',[name,phone,h,role]);res.json(rows[0])}catch(e){res.status(400).json({error:'Phone already exists or invalid data'})}});
app.patch('/api/users/:id',auth,admin,async(req,res)=>{const {name,phone,role,active,password}=req.body;if(password){const h=await bcrypt.hash(password,10);await pool.query('UPDATE users SET password_hash=$1 WHERE id=$2',[h,req.params.id])}if(name!==undefined)await pool.query('UPDATE users SET name=$1 WHERE id=$2',[name,req.params.id]);if(phone!==undefined)await pool.query('UPDATE users SET phone=$1 WHERE id=$2',[phone,req.params.id]);if(role!==undefined)await pool.query('UPDATE users SET role=$1 WHERE id=$2',[role,req.params.id]);if(active!==undefined)await pool.query('UPDATE users SET active=$1 WHERE id=$2',[active,req.params.id]);res.json({ok:true})});
app.post('/api/change-password',auth,async(req,res)=>{const h=await bcrypt.hash(req.body.password,10);await pool.query('UPDATE users SET password_hash=$1 WHERE id=$2',[h,req.user.id]);res.json({ok:true})});
app.get('/api/tasks',auth,async(req,res)=>{let q=`SELECT t.*,c.name company,u.name assignee,CASE WHEN t.status!='Completed' AND t.end_date<CURRENT_DATE THEN true ELSE false END overdue,CASE WHEN t.status!='Completed' AND t.end_date BETWEEN CURRENT_DATE AND CURRENT_DATE+2 THEN true ELSE false END due_soon FROM tasks t JOIN companies c ON c.id=t.company_id JOIN users u ON u.id=t.assigned_to`;let p=[];if(req.user.role!=='admin'){q+=' WHERE t.assigned_to=$1';p=[req.user.id]}q+=' ORDER BY t.end_date NULLS LAST,t.id DESC';res.json((await pool.query(q,p)).rows)});
app.post('/api/tasks',auth,admin,async(req,res)=>{const x=req.body;const {rows}=await pool.query(`INSERT INTO tasks(company_id,assigned_to,created_by,task_name,admin_remarks,start_date,end_date,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[x.company_id,x.assigned_to,req.user.id,x.task_name,x.admin_remarks,x.start_date,x.end_date,x.status||'Not Started']);const t=rows[0],code=`GC-${String(t.id).padStart(5,'0')}`;await pool.query('UPDATE tasks SET task_code=$1 WHERE id=$2',[code,t.id]);await snap(t.id,req.user.id,'Task created');await pool.query("INSERT INTO notifications(user_id,task_id,type,title,body) VALUES($1,$2,'assigned','New task assigned',$3)",[x.assigned_to,t.id,x.task_name]);res.json({...t,task_code:code})});
app.patch('/api/tasks/:id',auth,async(req,res)=>{const id=req.params.id;const {rows:[old]}=await pool.query('SELECT * FROM tasks WHERE id=$1',[id]);if(!old)return res.status(404).json({error:'Not found'});if(req.user.role!=='admin'&&old.assigned_to!==req.user.id)return res.status(403).json({error:'Forbidden'});const allowed=req.user.role==='admin'?['company_id','assigned_to','task_name','admin_remarks','start_date','end_date','status']:['status','admin_remarks'];for(const k of allowed)if(req.body[k]!==undefined)await pool.query(`UPDATE tasks SET ${k}=$1,updated_at=now() WHERE id=$2`,[req.body[k],id]);await snap(id,req.user.id,req.body.change_note||'Task updated');if(req.user.role!=='admin'){const {rows:[a]}=await pool.query("SELECT id FROM users WHERE role='admin' AND active=true");for(const u of a)await pool.query("INSERT INTO notifications(user_id,task_id,type,title,body) VALUES($1,$2,'task_update','Task updated',$3)",[u.id,id,`${old.task_code} updated by ${req.user.name}`])}res.json({ok:true})});
app.post('/api/tasks/:id/remarks',auth,async(req,res)=>{const id=req.params.id,{rows:[t]}=await pool.query('SELECT * FROM tasks WHERE id=$1',[id]);if(!t||(req.user.role!=='admin'&&t.assigned_to!==req.user.id))return res.status(403).json({error:'Forbidden'});await pool.query('INSERT INTO task_remarks(task_id,user_id,remark) VALUES($1,$2,$3)',[id,req.user.id,req.body.remark]);await snap(id,req.user.id,'Remark added');res.json({ok:true})});
app.get('/api/tasks/:id/history',auth,async(req,res)=>{const id=req.params.id,{rows:[t]}=await pool.query('SELECT * FROM tasks WHERE id=$1',[id]);if(!t||(req.user.role!=='admin'&&t.assigned_to!==req.user.id))return res.status(403).json({error:'Forbidden'});const history=(await pool.query('SELECT h.*,u.name changed_by_name FROM task_history h LEFT JOIN users u ON u.id=h.changed_by WHERE task_id=$1 ORDER BY version DESC',[id])).rows;const remarks=(await pool.query('SELECT r.*,u.name user_name FROM task_remarks r JOIN users u ON u.id=r.user_id WHERE task_id=$1 ORDER BY r.created_at DESC',[id])).rows;res.json({history,remarks})});
app.get('/api/notifications',auth,async(req,res)=>{await pool.query(`INSERT INTO notifications(user_id,task_id,type,title,body) SELECT t.assigned_to,t.id,'due_soon','Task due soon',t.task_code||' - '||t.task_name FROM tasks t WHERE t.status!='Completed' AND t.end_date=CURRENT_DATE+2 AND NOT EXISTS(SELECT 1 FROM notifications n WHERE n.user_id=t.assigned_to AND n.task_id=t.id AND n.type='due_soon' AND n.created_at::date=CURRENT_DATE)`);res.json((await pool.query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50',[req.user.id])).rows)});
app.get('/api/messages',auth,async(req,res)=>res.json((await pool.query('SELECT m.*,s.name sender_name,r.name receiver_name FROM messages m JOIN users s ON s.id=m.sender_id JOIN users r ON r.id=m.receiver_id WHERE sender_id=$1 OR receiver_id=$1 ORDER BY created_at DESC LIMIT 100',[req.user.id])).rows));
app.post('/api/messages',auth,async(req,res)=>{const {receiver_id,task_id,body}=req.body;await pool.query('INSERT INTO messages(sender_id,receiver_id,task_id,body) VALUES($1,$2,$3,$4)',[req.user.id,receiver_id,task_id||null,body]);res.json({ok:true})});
app.get('/health',(req,res)=>res.json({ok:true})); app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const port=process.env.PORT||3000;init().then(()=>app.listen(port,()=>console.log('Golden Circle running '+port))).catch(e=>{console.error(e);process.exit(1)});
